/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppLayout: typeof import('./resources/js/layouts/AppLayout.vue')['default']
    Create: typeof import('./resources/js/pages/Admin/Routes/Create.vue')['default']
    Index: typeof import('./resources/js/pages/Index.vue')['default']
    Login: typeof import('./resources/js/pages/Admin/Login.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NPageHeader: typeof import('naive-ui')['NPageHeader']
    NSpace: typeof import('naive-ui')['NSpace']
    RouteForm: typeof import('./resources/js/components/Routes/RouteForm.vue')['default']
    StopInput: typeof import('./resources/js/components/Routes/StopInput.vue')['default']
  }
}
