version: "3.1"
services:
  php:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    image: bus-php 
    container_name: bus-php
    tty: true
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html/
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: bus-nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html/
      - ./.docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  db:
    image: mariadb
    restart: always
    container_name: bus-mariadb
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    networks:
      - app-network
    
  node:
    image: node:19-bullseye-slim
    container_name: bus-node
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html/
    ports:
      - "5173:5173"
    command: bash -c "npm install && npm run dev"
    networks:
      - app-network
  
  adminer:
    image: adminer
    container_name: bus-adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DESIGN: dracula
    networks:
      - app-network
  
volumes:
  mariadb_data:
    driver: local

networks:
  app-network:
    driver: bridge
